BEGIN;

INSERT INTO public.contacts (client_id, first_name, last_name, full_name, email, phone, mobile, role, airtable_id)
VALUES
((SELECT id FROM public.clients WHERE client_code = 'Ameri' LIMIT 1), 'Daniela', 'Ameri', 'Daniela Ameri', 'd.ameri@americomunicazione.it', '+393356639635', NULL, NULL, 'recviMgZ1NzoCwyYM'),
((SELECT id FROM public.clients WHERE client_code = 'Ameri' LIMIT 1), 'Lorena', 'Ameri', 'Lorena Ameri', 'lorena@americomunicazione.it', '+393450433943', NULL, NULL, 'recCJiQpbtpfkWp1e'),
((SELECT id FROM public.clients WHERE client_code = 'Ameri' LIMIT 1), 'Victoria', 'Del Prete', 'Victoria Del Prete', 'staff@americomunicazione.it', '+393667210413', NULL, NULL, 'recEGjnLZ8Wd0mEct'),
((SELECT id FROM public.clients WHERE client_code = 'AESS,Renael' LIMIT 1), 'Alessio', 'Pecoraro', 'Alessio Pecoraro', 'alessio.pecoraro@aess.energy', '+393407124324', NULL, NULL, 'rechFmld0dnDZm0x7'),
((SELECT id FROM public.clients WHERE client_code = 'Aitek' LIMIT 1), 'Giorgio', 'Murruni', 'Giorgio Murruni', 'giorgio.murruni@aitek.it', '+393336227420', NULL, NULL, 'rec8AVcQBeEGTypbj'),
((SELECT id FROM public.clients WHERE client_code = 'Gulliver' LIMIT 1), 'Jennifer', 'Rubino', 'Jennifer Rubino', 'j.rubino@supergulliver.it', '+393427741062', NULL, NULL, 'rechqED2X3YxSCHEI'),
((SELECT id FROM public.clients WHERE client_code = 'Ausind' LIMIT 1), 'Daniela', 'Orengo', 'Daniela Orengo', 'dorengo@confindustria.ge.it', NULL, NULL, NULL, 'rec0C37nXepq7zdxk'),
((SELECT id FROM public.clients WHERE client_code = 'Ceis' LIMIT 1), 'Alessandro', 'Censi Buffarini', 'Alessandro Censi Buffarini', 'relazioniesterne@ceisge.org', '+393474407887', NULL, NULL, 'recw7kkvxpBrzzyS9'),
((SELECT id FROM public.clients WHERE client_code = 'Start 4.0' LIMIT 1), 'Uberto', 'Cremonini', 'Uberto Cremonini', 'uberto.cremonini@start4-0.it', NULL, NULL, NULL, 'receNAX5teowy1IAy'),
((SELECT id FROM public.clients WHERE client_code = 'Confindustria Genova' LIMIT 1), 'Piera', 'Ponta', 'Piera Ponta', 'pponta@confindustria.ge.it', '+393357623390', NULL, NULL, 'rec7SlbqQmfKYqw8L'),
((SELECT id FROM public.clients WHERE client_code = 'Confindustria Genova' LIMIT 1), 'Giuliana', 'De Lucchi', 'Giuliana De Lucchi', 'gdelucchi@confindustria.ge.it', '+393351830289', NULL, NULL, 'rec32ljLPwCUuKXeo'),
((SELECT id FROM public.clients WHERE client_code = 'Confindustria Genova' LIMIT 1), 'Matilde', 'Orlando', 'Matilde Orlando', 'morlando@confindustria.ge.it', '+393316326881', NULL, NULL, 'recqhKhCeaaAnLGhq'),
((SELECT id FROM public.clients WHERE client_code = 'DIHL' LIMIT 1), 'Lorenzo', 'Costa', 'Lorenzo Costa', 'lcosta@dihliguria.it', '+393336147757', NULL, NULL, 'recnLREPD45ulaY8Z'),
((SELECT id FROM public.clients WHERE client_code = 'Edilporta' LIMIT 1), 'Diamila', 'Musso', 'Diamila Musso', 'info@edilporta.net', '+393488597769', NULL, NULL, 'recIhSF54ps5tYrI9'),
((SELECT id FROM public.clients WHERE client_code = 'Cofoundry' LIMIT 1), 'Erica', 'Turchetti', 'Erica Turchetti', 'erica@cofoundry.it', '+393398586128', NULL, NULL, 'recGfXuwyfgXP0qYF'),
((SELECT id FROM public.clients WHERE client_code = 'Cofoundry' LIMIT 1), 'Giulia', 'Leoni', 'Giulia Leoni', 'giulia@cofoundry.it', '+393463152966', NULL, NULL, 'recrZCZ4sUYd5TLVM'),
((SELECT id FROM public.clients WHERE client_code = 'F.lli Razeto e Casareto' LIMIT 1), 'Giangi', 'Razeto', 'Giangi Razeto', NULL, '+393357711315', NULL, NULL, 'recs06UrK2pEucqT0'),
((SELECT id FROM public.clients WHERE client_code = 'GFCL' LIMIT 1), 'Claudia', 'Oliva', 'Claudia Oliva', 'claudia22_oliva@yahoo.it', '+393396843218', NULL, NULL, 'reckDBpLFi88Zz2nv'),
((SELECT id FROM public.clients WHERE client_code = 'IIT - Istituto Italiano di Tecnologia' LIMIT 1), 'Sabrina', 'Peloso', 'Sabrina Peloso', 'Sabrina.Peloso@iit.it', '+ 390102896807', NULL, NULL, 'rec4OutNkzmRw3zPL'),
((SELECT id FROM public.clients WHERE client_code = 'IIT - Istituto Italiano di Tecnologia' LIMIT 1), 'Stefano', 'Maludrottu', 'Stefano Maludrottu', 'Stefano.Maludrottu@iit.it', '+393283821826', NULL, NULL, 'recPJlSLAQSya9KjM'),
((SELECT id FROM public.clients WHERE client_code = 'Fos' LIMIT 1), 'Ilaria', 'Leopoldo', 'Ilaria Leopoldo', 'Ilaria.Leopoldo@fos.it', '+393460281817', NULL, NULL, 'recjESgzdgzzVJHi9'),
((SELECT id FROM public.clients WHERE client_code = 'Gruppo Frama' LIMIT 1), 'Francesca', 'Fratea', 'Francesca Fratea', 'info@locandadatoto.it', '+393272052685', NULL, NULL, 'recf1iTA3S4Q64p9k'),
((SELECT id FROM public.clients WHERE client_code = 'Hotel Savoia' LIMIT 1), 'Gabriele', 'Fortunato', 'Gabriele Fortunato', 'gabriele.fortunato@hotelsavoiagenova.it', '+393355732844', NULL, NULL, 'recv8D4EV57CTrDJP'),
((SELECT id FROM public.clients WHERE client_code = 'Hotel Savoia' LIMIT 1), 'Silvia', 'Patrone', 'Silvia Patrone', 'congressi@hotelsavoiagenova.it', NULL, NULL, NULL, 'recrmMus9bQF7vh14'),
((SELECT id FROM public.clients WHERE client_code = 'Hotel Savoia' LIMIT 1), 'Gloria', 'De Palo', 'Gloria De Palo', 'sales@hotelsavoiagenova.it', NULL, NULL, NULL, 'rec8TWiey0KyDswQC'),
((SELECT id FROM public.clients WHERE client_code = 'Casaviva' LIMIT 1), 'Andrea', 'Della Porta', 'Andrea Della Porta', 'andrea.dellaporta@casavivaservice.it', '+393896833717', NULL, NULL, 'rec2MY8rSF9dhWPUo'),
((SELECT id FROM public.clients WHERE client_code = 'Casaviva' LIMIT 1), 'Cinzia', 'Di Barbara', 'Cinzia Di Barbara', 'cinzia@casavivaservice.it', '+393331543384', NULL, NULL, 'recs1C1aqEtKGqffD'),
((SELECT id FROM public.clients WHERE client_code = 'Pittaluga' LIMIT 1), 'Nicolò', 'Cogorno', 'Nicolò Cogorno', 'info@tendetessutigenova.it', '+393496890202', NULL, NULL, 'recWLKSNDoKAP1GbL'),
((SELECT id FROM public.clients WHERE client_code = 'Teseo Rooms & Relax' LIMIT 1), 'Roberto', 'Riggi', 'Roberto Riggi', 'impresa@robertoriggi.com', '+39335318868', NULL, NULL, 'rectpqqs985YbYKws'),
((SELECT id FROM public.clients WHERE client_code = 'Studio Condello Borsei' LIMIT 1), 'Silvia', 'Condello', 'Silvia Condello', 'info@studiocondelloborsei.it', NULL, NULL, NULL, 'recuHLdPBWMHpEzRV'),
((SELECT id FROM public.clients WHERE client_code = 'Aqua' LIMIT 1), 'Maia', 'Nogaro', 'Maia Nogaro', NULL, '+393407222671', NULL, NULL, 'rec2oc74sok2W0YZd'),
((SELECT id FROM public.clients WHERE client_code = 'Fanimar' LIMIT 1), 'Gabriella', 'Caorsi', 'Gabriella Caorsi', 'gabriella.caorsi@fanimar.it', '+393403488412', NULL, NULL, 'recDK71HP7LlwtJtv'),
((SELECT id FROM public.clients WHERE client_code = 'Start 4.0' LIMIT 1), 'Nagwa', 'Ibrahim', 'Nagwa Ibrahim', 'nagwa.ibrahim@start4-0.it', '+393496514214', NULL, NULL, 'recrBZ6LlCfNDoWZ4'),
((SELECT id FROM public.clients WHERE client_code = 'TARA BIANCA' LIMIT 1), 'Matteo', 'Laffranchi', 'Matteo  Laffranchi', 'matt.laffranchi@gmail.com', '(329) 202-7216', NULL, NULL, 'recAPsaOEJvioufsf'),
((SELECT id FROM public.clients WHERE client_code = 'Partito Democratico di Genova e della Liguria ,Serteco Volley School Genova' LIMIT 1), 'Andrea', 'Casassa', 'Andrea  Casassa', NULL, '(347) 231-9075', NULL, NULL, 'recYURULYFjix3rh6'),
((SELECT id FROM public.clients WHERE client_code = 'Banchero Costa Insurance' LIMIT 1), 'Alda', 'Santini', 'Alda Santini', 'santini@bancosta.com', '+39 010 563125', NULL, NULL, 'recZ8TpksD8gAgaDQ'),
((SELECT id FROM public.clients WHERE client_code = 'Ordine Ingegneri Genova' LIMIT 1), 'Georgia', 'Cesarone', 'Georgia  Cesarone', 'georgia.cesarone@start4-0.it', NULL, '(340) 309-7542', NULL, 'rec5yunhlhc6uWh8g'),
((SELECT id FROM public.clients WHERE client_code = 'Fabio Gilardi Sindaco' LIMIT 1), 'Fabio', 'Gilardi', 'Fabio  Gilardi', 'Gilardif@gmail.com', NULL, '(347) 964-7357', NULL, 'recFMNQHwMMhNQnVw'),
((SELECT id FROM public.clients WHERE client_code = 'PRESSCOMM TECH' LIMIT 1), 'Nicola', 'Reineri', 'Nicola Reineri', 'n.reineri@presscommtech.com', NULL, '+39 3389959656', NULL, 'recilOUM0S1Sb7Kmd'),
((SELECT id FROM public.clients WHERE client_code = 'Gruppo Consiliare PD Regione Liguria' LIMIT 1), 'Lara', 'Pizzorno', 'Lara  Pizzorno', 'Lara.Pizzorno@regione.liguria.it', NULL, NULL, NULL, 'recr9slPEPJeyYPeb'),
((SELECT id FROM public.clients WHERE client_code = 'Columbia Group SRL' LIMIT 1), 'Cristina', 'Carnevali', 'Cristina Carnevali', 'Cristina.Carnevali@unige.it', NULL, NULL, NULL, 'recb7YSEQCiUatSgo'),
((SELECT id FROM public.clients WHERE client_code = NULL LIMIT 1), 'Roberto', 'Arboscello', 'Roberto  Arboscello', 'arboscelloinregione@gmail.com', NULL, NULL, NULL, 'recfIOuYh6Ot9j0kV'),
((SELECT id FROM public.clients WHERE client_code = 'Ecosteer S.r.l.' LIMIT 1), 'Elena', 'Pasquali', 'Elena  Pasquali', 'elena.pasquali@ecosteer.com', NULL, NULL, NULL, 'recvjhcqrcKpuq6ZR'),
((SELECT id FROM public.clients WHERE client_code = 'Chiappe Revello' LIMIT 1), 'Elena', 'Baccini', 'Elena  Baccini', 'e.baccini@chiapperevello.it', NULL, '(348) 996-7037', NULL, 'recJyb0cig8mpD7xV'),
((SELECT id FROM public.clients WHERE client_code = 'Camera di Commercio Genova' LIMIT 1), 'Serena', 'Pagliosa', 'Serena  Pagliosa', 'serena.pagliosa@ge.camcom.it', '(340) 304-1579', NULL, NULL, 'rec8bnTCroo5zFg2e'),
((SELECT id FROM public.clients WHERE client_code = 'Comitato elettorale Andrea Orlando' LIMIT 1), 'Vittoria', 'Canessa', 'Vittoria  Canessa', NULL, NULL, '(342) 012-1967', NULL, 'recG0iGAQNQ38dkXA'),
((SELECT id FROM public.clients WHERE client_code = 'Start 4.0' LIMIT 1), 'Andrea', 'Visentin', 'Andrea Visentin', 'davide@davidegentile.it', '40324758325734982', NULL, 'Comunicazione', 'recIOjpgUOGHm5ZWT'),
((SELECT id FROM public.clients WHERE client_code = 'CNR IMATI' LIMIT 1), 'Franca', 'Giannini', 'Franca Giannini', 'franca.giannini@ge.imati.cnr.it', NULL, '+393473804197', NULL, 'recFRLrj7olC5VIti'),
((SELECT id FROM public.clients WHERE client_code = 'SEC AND PARTNERS' LIMIT 1), 'Licia', 'Mazzoni', 'Licia Mazzoni', 'licia.mazzoni@secnewgate.it', NULL, '+39 347 4413166', NULL, 'recYoNDjztZTdVHvY')
ON CONFLICT (airtable_id) DO UPDATE SET
client_id = EXCLUDED.client_id, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, full_name = EXCLUDED.full_name, email = EXCLUDED.email, phone = EXCLUDED.phone, mobile = EXCLUDED.mobile, role = EXCLUDED.role;

COMMIT;