-- 1. Add fields to passive_invoices if they don't exist
ALTER TABLE public.passive_invoices 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS service_description TEXT,
ADD COLUMN IF NOT EXISTS related_orders JSONB,
ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount_tax_included NUMERIC(15,2),
ADD COLUMN IF NOT EXISTS amount_tax_excluded NUMERIC(15,2),
ADD COLUMN IF NOT EXISTS vat_rate NUMERIC(5,2),
ADD COLUMN IF NOT EXISTS vat_eligibility TEXT,
ADD COLUMN IF NOT EXISTS attachment_url TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Da Pagare',
ADD COLUMN IF NOT EXISTS payment_date DATE,
ADD COLUMN IF NOT EXISTS category TEXT,
ADD COLUMN IF NOT EXISTS ritenuta NUMERIC(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS rivalsa_inps NUMERIC(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS stamp_duty NUMERIC(15,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS iva_attiva BOOLEAN DEFAULT false;

-- 2. Add fields to suppliers table for fiscal data
ALTER TABLE public.suppliers
ADD COLUMN IF NOT EXISTS vat_number TEXT,
ADD COLUMN IF NOT EXISTS tax_code TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS zip_code TEXT,
ADD COLUMN IF NOT EXISTS province TEXT,
ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'IT',
ADD COLUMN IF NOT EXISTS fiscal_regime TEXT DEFAULT 'ordinario',
ADD COLUMN IF NOT EXISTS default_vat_rate NUMERIC(5,2) DEFAULT 22,
ADD COLUMN IF NOT EXISTS cassa_previdenziale_rate NUMERIC(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS withholding_tax_rate NUMERIC(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS payment_terms TEXT,
ADD COLUMN IF NOT EXISTS bank_iban TEXT;

-- 3. Force schema cache reload (crucial for PGRST204 error)
NOTIFY pgrst, 'reload config';
